Repository archivesspace/archivesspace, pull requests merged in 2018-04, with the labels that each got.

#1180 ANW-248 Update Collection Management sort labels
  common/locales/en.yml
  frontend/config/locales/en.yml
  frontend/config/locales/es.yml
  frontend/config/locales/fr.yml
Labels: in progress

#1185 ANW-246 Add Record Type to Agents sort
  frontend/app/views/shared/_pagination_summary.html.erb
Labels: in progress

#1199 ANW 314 deaccessions
  backend/Gemfile.lock
  build/build.xml
  frontend/Gemfile
  frontend/Gemfile.lock
  indexer/Gemfile
  indexer/Gemfile.lock
  public/Gemfile
  public/Gemfile.lock
  public/app/models/accession.rb
  public/spec/controllers/accessions_controller_spec.rb
  public/spec/factories.rb
  selenium/Gemfile
  selenium/Gemfile.lock
Labels: in progress

#1194 ANW-307: Update documentation and remove URL to outdated demo database
  backend/app/lib/bootstrap.rb
  common/config/config-defaults.rb
Labels: in progress

#1197 ANW-236 Add subjects to pui search options
  public/app/views/repositories/show.html.erb
  public/app/views/search/search_results.html.erb
  public/app/views/welcome/show.html.erb
  public/config/locales/en.yml
Labels: community, in progress

#1201 Improve API documentation
  _yard/API.erb
Labels: community

#1202 Fix broken test and update all tests to RSpec expect syntax
  backend/spec/controller_agent_person_spec.rb
  backend/spec/export_marc_spec.rb
  indexer/app/lib/periodic_indexer.rb
Labels: in progress

#1209 ANW-193 Add personalTitle and relator to accession CSV import
  backend/app/converters/accession_converter.rb
  backend/app/exporters/examples/accession/aspace_accession_import_template.csv
Labels: in progress

#1192 ANW-677: json-ld language fix
  public/app/models/resource.rb
Labels: community

#1217 ANW-687-fix
  stylesheets/as-ead-pdf.xsl
Labels: community

#1218 Set default search operator to AND in AppConfig
  backend/spec/model_solr_spec.rb
  common/config/config-defaults.rb
Labels: in progress

#1225 update jruby: issue #1224
  build/build.xml
Labels: in progress

#1227 relatedmaterial repeated in public locales files
  public/config/locales/en.yml
  public/config/locales/fr.yml
Labels: in progress
