Repository archivesspace/archivesspace, pull requests merged in 2020-10, with the labels that each got.

#1987 Spanish translations for the public interface
  public/config/locales/es.yml
Labels: hacktoberfest_2020, translations

#1989 Bump json to 2.3.0 for apps
  backend/Gemfile
  backend/Gemfile.lock
  frontend/Gemfile
  frontend/Gemfile.lock
  indexer/Gemfile
  indexer/Gemfile.lock
  public/Gemfile
  public/Gemfile.lock
Labels: gem management, hacktoberfest_2020

#1992 Upgrade rails to v5.2.4.4
  backend/Gemfile
  backend/Gemfile.lock
  docs/Gemfile.lock
  frontend/Gemfile
  frontend/Gemfile.lock
  indexer/Gemfile
  indexer/Gemfile.lock
  public/Gemfile
  public/Gemfile.lock
Labels: gem management, hacktoberfest_2020, version updates

#1990 ANW-1116: Don't update merge target for agent merges
  backend/app/controllers/merge_request.rb
  backend/app/lib/rest.rb
  backend/app/model/mixins/relationships.rb
  backend/spec/rest_merge_request_spec.rb
Labels: API, bug, hacktoberfest_2020

#1994 ANW-1016 - Suppress button color consistency
  frontend/app/assets/javascripts/enumerations.index.js
  frontend/app/views/enumerations/_list.html.erb
  frontend/app/views/enumerations/_merge.html.erb
Labels: hacktoberfest-accepted

#1889 Browse location by repository facet
  backend/app/model/location.rb
  common/config/search_browse_column_config.rb
  frontend/app/controllers/locations_controller.rb
  frontend/app/models/search.rb
  frontend/app/models/search_result_data.rb
  frontend/app/views/locations/show.html.erb
  frontend/app/views/search/_filter.html.erb
  frontend/config/locales/en.yml
  indexer/app/lib/indexer_common.rb
Labels: community, in progress, migration_needed

#1959 ANW-921: Make citation tab configurable, use translations
  common/config/config-defaults.rb
  public/app/views/cite/_modal_tabbed.html.erb
  public/config/locales/en.yml
  public/config/locales/es.yml
  public/config/locales/fr.yml
  public/config/locales/ja.yml
  public/spec/features/cite_spec.rb
Labels: config_changes, in progress, translations, update_release_notes

#2000 Adds recommendation to restrict API access
  _yard/API.erb
Labels: API, documentation, hacktoberfest-accepted

#1995 Spanish and Japanese translations for reports
  reports/accessions/accession_classifications_subreport/es.yml
  reports/accessions/accession_classifications_subreport/ja.yml
  reports/accessions/accession_deaccessions_list_report/es.yml
  reports/accessions/accession_deaccessions_list_report/ja.yml
  reports/accessions/accession_deaccessions_subreport/es.yml
  reports/accessions/accession_inventory_report/es.yml
  reports/accessions/accession_inventory_report/ja.yml
  reports/accessions/accession_receipt_report/es.yml
  reports/accessions/accession_receipt_report/ja.yml
  reports/accessions/accession_report/es.yml
  reports/accessions/accession_report/ja.yml
  reports/accessions/accession_rights_transferred_report/es.yml
  reports/accessions/accession_rights_transferred_report/ja.yml
  reports/accessions/accession_subjects_names_classifications_list_report/es.yml
  reports/accessions/accession_subjects_names_classifications_list_report/ja.yml
  reports/accessions/accession_unprocessed_report/es.yml
  reports/accessions/accession_unprocessed_report/ja.yml
  reports/accessions/created_accessions_report/es.yml
  reports/accessions/created_accessions_report/ja.yml
  reports/agents/agent_list_report/es.yml
  reports/agents/agent_list_report/ja.yml
  reports/assessments/assessment_list_report/es.yml
  reports/assessments/assessment_list_report/ja.yml
  reports/digital_objects/digital_object_file_versions_report/es.yml
  reports/digital_objects/digital_object_file_versions_report/ja.yml
  reports/digital_objects/digital_object_list_table_report/es.yml
  reports/digital_objects/digital_object_list_table_report/ja.yml
  reports/locations/location_holdings_report/es.yml
  reports/locations/location_holdings_report/ja.yml
  reports/locations/location_report/es.yml
  reports/locations/location_report/ja.yml
  reports/locations/shelflist_report/es.yml
  reports/locations/shelflist_report/fr.yml
  reports/locations/shelflist_report/ja.yml
  reports/resources/resource_deaccessions_list_report/es.yml
  reports/resources/resource_deaccessions_list_report/ja.yml
  reports/resources/resource_instances_list_report/es.yml
  reports/resources/resource_instances_list_report/ja.yml
  reports/resources/resource_locations_list_report/es.yml
  reports/resources/resource_locations_list_report/ja.yml
  reports/resources/resource_restrictions_list_report/es.yml
  reports/resources/resource_restrictions_list_report/ja.yml
  reports/resources/resources_list_report/es.yml
  reports/resources/resources_list_report/fr.yml
  reports/resources/resources_list_report/ja.yml
  reports/subjects/subject_list_report/es.yml
  reports/subjects/subject_list_report/ja.yml
  reports/users/user_groups_report/ja.yml
Labels: hacktoberfest-accepted, reports, translations

#1993 Prefs table columns with context condition
  common/config/search_browse_column_config.rb
  frontend/app/helpers/search_helper.rb
  plugins/custom_browse_search_column/README.md
  plugins/custom_browse_search_column/search_browse_column_plugin_config.rb
Labels: add_technical_documentation, hacktoberfest-accepted, plugins

#1997 Continuation of #1889 to add migration, test, label changes
  common/db/migrations/137_reindex_locations.rb
  frontend/app/models/search.rb
  frontend/app/models/search_result_data.rb
  frontend/app/views/search/_filter.html.erb
  frontend/spec/selenium/spec/locations_spec.rb
Labels: hacktoberfest-accepted, migration

#2001 Small update to French translations for PUI
  public/config/locales/fr.yml
Labels: hacktoberfest-accepted, translations

#2002 Adds a few Spanish and French translations
  frontend/config/locales/es.yml
  frontend/config/locales/fr.yml
Labels: hacktoberfest-accepted, translations

#2003 Update AppConfig from env options
  common/config/config-distribution.rb
  common/spec/appconfig_spec.rb
Labels: add_technical_documentation, devservers, hacktoberfest-accepted

#1985 ANW-1111 Fixes PUI Print to PDF Fails if & Followed by a Capital Letter
  public/app/lib/xml_cleaner.rb
Labels: PDF

#1984 Adds provenance to the accession_report
  reports/accessions/accession_report/accession_report.rb
  reports/static/translation_defaults/en.yml
  reports/static/translation_defaults/es.yml
  reports/static/translation_defaults/fr.yml
Labels: hacktoberfest-accepted, reports

#2006 Add langcode value+translation back into yml files
  frontend/config/locales/en.yml
  frontend/config/locales/es.yml
  frontend/config/locales/fr.yml
  frontend/config/locales/ja.yml
Labels: hacktoberfest-accepted, translations

#1935 ANW-992: Remove missing methods from set_access_control
  frontend/app/controllers/archival_objects_controller.rb
  frontend/app/controllers/classification_terms_controller.rb
  frontend/app/controllers/jobs_controller.rb
Labels: cleanup

#1978 ANW-750: Update MARCXML 544 field import
  backend/app/converters/lib/marcxml_base_map.rb
  backend/spec/lib_marcxml_converter_spec.rb
Labels: community, import / export

#2011 Bulk import tests need to be a bit more patient
  frontend/spec/selenium/spec/bulk_import_spec.rb
Labels: hacktoberfest-accepted, tests

#2012 ANW-1129: Use translations for PUI container type filter
  public/app/controllers/concerns/handle_faceting.rb
Labels: hacktoberfest-accepted, pui

#1998 ANW-903 Fixes EAD uniform title import
  backend/app/converters/ead_converter.rb
  backend/spec/lib_ead_converter_spec.rb
Labels: hacktoberfest-accepted, import / export

#1968 Fixes/enhancements to staff side pdfs
  backend/Gemfile
  backend/Gemfile.lock
  backend/app/lib/AS_fop.rb
  stylesheets/as-ead-pdf.xsl
Labels: PDF, bug

#1999 Branding Image URL tooltip wording change
  common/locales/en.yml
Labels: hacktoberfest-accepted, translations, translations_needed

#2020 Additional translations for the updated Branding Image URL tooltip
  common/locales/es.yml
  common/locales/fr.yml
  common/locales/ja.yml
Labels: hacktoberfest-accepted, translations

#2008 Hm qsa 092820 mc
  backend/app/lib/nested_record_resolver.rb
  backend/app/model/backend_enum_source.rb
  backend/app/model/mixins/dynamic_enums.rb
  backend/app/model/mixins/relationships.rb
  backend/app/model/mixins/tree_nodes.rb
  backend/spec/controller_enumeration_spec.rb
  common/aspace_i18n_enumeration_support.rb
  common/json_schema_utils.rb
  common/spec/lib/factory_bot_helpers.rb
  frontend/app/assets/javascripts/subrecord.collapsible.js
  frontend/app/helpers/aspace_form_helper.rb
  frontend/app/views/agents/_form.html.erb
  frontend/app/views/agents/_form_required.html.erb
  frontend/app/views/groups/edit.html.erb
  frontend/app/views/notes/_template.html.erb
  frontend/app/views/shared/_form_messages.html.erb
  frontend/app/views/shared/_subrecord_form.html.erb
  frontend/config/initializers/i18n.rb
  frontend/spec/selenium/spec/subjects_spec.rb
Labels: community, hacktoberfest-accepted

#2019 ANW-1126: Add alt text to logo images in staff and PUI
  common/config/config-defaults.rb
  frontend/app/views/site/_branding.html.erb
  public/app/views/shared/_header.html.erb
Labels: accessibility, config_changes, hacktoberfest-accepted, pui

#2015 Hide bulk import from create dropdown menu
  frontend/app/views/shared/_header_repository.html.erb
Labels: hacktoberfest-accepted

#2018 ANW-1130: Don't error when a dig obj comp only has a date
  backend/app/model/digital_object_component.rb
Labels: bug, hacktoberfest-accepted

#2021 ANW-631 cont'd: Also include the doid in a digital object typeahead
  frontend/app/assets/javascripts/linker.js
Labels: feature_request, hacktoberfest-accepted

#2017 ANW-757: Stop mapping dao titles to captions
  backend/app/converters/ead_converter.rb
Labels: hacktoberfest-accepted, import / export

#2024 Continuation of #2015 to hide Load Spreadsheet
  frontend/app/views/jobs/index.html.erb
Labels: hacktoberfest-accepted

#2025 Minor fix-ups to bulk import locales
  backend/spec/lib_bulk_import_bulk_import_mixins_spec.rb
  backend/spec/lib_bulk_import_bulk_mixins_spec.rb
  backend/spec/lib_bulk_import_lang_handler_spec.rb
  backend/spec/lib_bulk_import_notes_handler_spec.rb
  common/locales/en.yml
Labels: hacktoberfest-accepted, translations

#2027 Bulk import tweaks
  backend/app/lib/bulk_import/agent_handler.rb
  backend/app/lib/bulk_import/bulk_import_parser.rb
  backend/app/lib/bulk_import/digital_object_handler.rb
  backend/app/lib/bulk_import/import_digital_objects.rb
  backend/spec/lib_bulk_import_agent_handler_spec.rb
Labels: hacktoberfest-accepted

#2029 Style improvements for bulk import modal
  frontend/app/assets/javascripts/bulk_import.js.erb
  frontend/app/assets/stylesheets/archivesspace/buttons.less
  frontend/app/views/resources/_bulk_import_form.html.erb
Labels: accessibility, hacktoberfest-accepted

#2028 Update bulk import template files to match
  templates/bulk_import_DO_template.csv
  templates/bulk_import_DO_template.xlsx
  templates/bulk_import_template.csv
  templates/bulk_import_template.xlsx
Labels: hacktoberfest-accepted, templates

#2026 Don't show files unless job complete, show bulk_import form fields
  frontend/app/views/jobs/_show_templates.html.erb
  frontend/app/views/jobs/show.html.erb
Labels: hacktoberfest-accepted

#2036 Update Total Processing Hours for Collection Management CRUD js
  frontend/app/assets/javascripts/collection_management_records.crud.js
Labels: bug, community, hacktoberfest-accepted

#2034 Fixes Agent required fields view
  frontend/app/views/agents/_form_required.html.erb
Labels: community, hacktoberfest-accepted

#2032 Fix to agent handler assigning wrong agents
  backend/app/lib/bulk_import/agent_handler.rb
Labels: community, hacktoberfest-accepted

#2037 Prevent bulk import from creating date types
  backend/app/lib/bulk_import/bulk_import_mixins.rb
Labels: community, hacktoberfest-accepted

#2033 ANW-1099, ANW-776, ANW-1008: Search/browse column improvements
  common/config/search_browse_column_config.rb
  common/locales/en.yml
  common/locales/es.yml
  common/locales/fr.yml
  common/locales/ja.yml
  frontend/app/helpers/search_helper.rb
  frontend/app/views/defaults/_template.html.erb
  frontend/app/views/preferences/_sidebar.html.erb
  frontend/app/views/preferences/edit.html.erb
  frontend/app/views/search/_langcode_cell.html.erb
  frontend/app/views/shared/_sidebar_entry.html.erb
  frontend/config/locales/en.yml
  frontend/config/locales/es.yml
  frontend/config/locales/fr.yml
  frontend/config/locales/ja.yml
Labels: feature_request, hacktoberfest-accepted

#2038 Make repo scoped breadcrumbs appear consistently & add type in all cases
  public/app/controllers/accessions_controller.rb
  public/app/controllers/classifications_controller.rb
  public/app/controllers/concerns/searchable.rb
  public/app/controllers/containers_controller.rb
  public/app/controllers/resources_controller.rb
  public/app/helpers/record_helper.rb
  public/app/models/tree.rb
Labels: hacktoberfest-accepted, pui

#2040 Provide a direct method to deprecate a config property.
  common/config/config-aliases.rb
  common/config/config-defaults.rb
  common/config/config-distribution.rb
Labels: cleanup, config_changes, hacktoberfest-accepted

#2041 No escape on note exception message
  backend/app/lib/bulk_import/bulk_import_mixins.rb
  backend/app/lib/bulk_import/lang_handler.rb
  backend/app/lib/bulk_import/notes_handler.rb
  common/locales/en.yml
Labels: hacktoberfest-accepted
