Repository archivesspace/archivesspace, pull requests merged in 2020-03, with the labels that each got.

#1792 ANW-1018: Add language facet
  frontend/app/models/search_result_data.rb
  frontend/config/locales/en.yml
  indexer/app/lib/indexer_common.rb
  public/app/controllers/concerns/handle_faceting.rb
  public/app/controllers/objects_controller.rb
  public/app/controllers/resources_controller.rb
  public/app/controllers/search_controller.rb
  public/app/views/shared/_only_facets.html.erb
  public/config/locales/en.yml
  solr/schema.xml
Labels: community

#1836 Fixes for backend tests run with MySQL
  backend/app/controllers/batch_import.rb
  backend/app/model/mixins/reindex_top_containers.rb
  backend/app/model/sequence.rb
  backend/spec/mixin_touch_records_spec.rb
  backend/spec/model_asmodel_spec.rb
  backend/spec/model_managed_container_spec.rb
  backend/spec/model_relationships_spec.rb
  backend/spec/model_sequence_spec.rb
  backend/spec/spec_helper.rb
Labels: add_documentation

#1780 fix for json ld when dates of existence lacked a begin or end value i…
  public/app/models/agent_corporate_entity.rb
  public/app/models/agent_family.rb
  public/app/models/agent_person.rb
Labels: community

#1813 ANW-1040 Replace saxon-xslt gem with saxon-rb
  backend/Gemfile
  backend/Gemfile.lock
  backend/app/lib/AS_fop.rb
  backend/app/lib/AS_fop_external.rb
Labels: community

#1829 Pass resource record to PUI PDF footer template
  public/app/models/finding_aid_pdf.rb
Labels: community

#1831 Make displaying search-in-collection form configurable option in other contexts
  common/config/config-defaults.rb
  public/app/views/objects/show.html.erb
  public/app/views/resources/infinite.html.erb
  public/app/views/resources/show.html.erb
  public/app/views/shared/_search_collection_form.html.erb
Labels: community, config_changes, update_release_notes

#1823 Create SECURITY.md
  SECURITY.md
Labels: documentation
