Repository archivesspace/archivesspace, pull requests merged in 2020-06, with the labels that each got.

#1914 Re-add pieces from GTIC and some cleanup after browse / search
  common/config/search_browse_column_config.rb
  frontend/app/assets/stylesheets/archivesspace/tables.less
  frontend/app/assets/stylesheets/archivesspace/top_containers_bulk.less
  frontend/app/controllers/assessments_controller.rb
  frontend/app/controllers/locations_controller.rb
  frontend/app/controllers/search_controller.rb
  frontend/app/helpers/search_helper.rb
  frontend/app/views/accessions/_linker.html.erb
  frontend/app/views/agents/show.html.erb
  frontend/app/views/assessments/_agent_linker.html.erb
  frontend/app/views/assessments/_records_linker.html.erb
  frontend/app/views/resources/_linker.html.erb
  frontend/app/views/top_containers/bulk_operations/_results.html.erb
  indexer/app/lib/indexer_common.rb
Labels: indexer

#1916 Fix container profile merge modal to re-add display strings
  frontend/app/assets/javascripts/browse_merge.js
  frontend/app/views/shared/_multiselect.html.erb
  frontend/spec/selenium/spec/container_profiles_spec.rb
Labels: bug

#1917 Change the default sort of jobs index to time_submitted
  common/config/preference_defaults.rb
  common/config/search_browse_column_config.rb
  common/locales/en.yml
  common/locales/es.yml
  common/locales/fr.yml
  common/locales/ja.yml
  frontend/config/locales/en.yml
  frontend/config/locales/es.yml
  frontend/config/locales/fr.yml
  frontend/config/locales/ja.yml
Labels: config_changes, translations

#1919 Use correct search controller from top container location browse
  frontend/app/views/top_containers/bulk_operations/_location_linker.html.erb
Labels: bug

#1924 Fix select_all deletion
  frontend/app/assets/javascripts/search.js
  frontend/spec/selenium/spec/accessions_spec.rb
Labels: bug

#1921 Updates for pui search
  backend/app/model/search.rb
  backend/app/model/solr.rb
  indexer/app/lib/indexer_common.rb
  indexer/app/lib/large_tree_doc_indexer.rb
  indexer/app/lib/pui_indexer.rb
  public/app/helpers/view_helper.rb
  public/app/models/finding_aid_pdf.rb
  public/app/models/record.rb
  public/app/services/archives_space_client.rb
  public/app/views/resources/_infinite_item.html.erb
  public/app/views/shared/_idbadge.html.erb
  solr/schema-6.6.xml
  solr/schema.xml
Labels: bug, indexer

#1923 Make subjects subject and fix csv and sort
  common/config/preference_defaults.rb
  common/config/search_browse_column_config.rb
  frontend/app/controllers/subjects_controller.rb
  frontend/app/helpers/search_helper.rb
  frontend/app/models/search_result_data.rb
  frontend/config/locales/en.yml
  frontend/config/locales/es.yml
  frontend/config/locales/fr.yml
  frontend/config/locales/ja.yml
Labels: bug, translations

#1932 ANW-138: Save changes that don't involve cursor activity
  frontend/app/assets/javascripts/mixed_content.js
Labels: bug

#1939 ANW-462 cont: Reindex target post merge
  backend/app/model/mixins/relationships.rb
Labels: bug
