Repository archivesspace/archivesspace, pull requests merged in 2020-08, with the labels that each got.

#1958 Update the release notes task to highlight deprecated endpoints
  scripts/tasks/release_notes.rb
Labels: documentation

#1962 Update to account for id.loc.gov moving from http to https
  plugins/lcnaf/frontend/assets/lcnaf.js
  plugins/lcnaf/frontend/controllers/lcnaf_controller.rb
  plugins/lcnaf/frontend/locales/en.yml
  plugins/lcnaf/frontend/locales/fr.yml
  plugins/lcnaf/frontend/models/opensearcher.rb
  plugins/lcnaf/frontend/spec/lcnaf_client_spec.rb
  plugins/lcnaf/frontend/views/lcnaf/index.html.erb
Labels: plugins

#1960 Removes code related to unimplemented bookbag feature
  common/config/config-defaults.rb
  public/config/initializers/public_new_defaults.rb
  public/config/locales/en.yml
  public/config/locales/es.yml
  public/config/locales/fr.yml
  public/config/locales/ja.yml
Labels: cleanup, config_changes, translations

#1955 ANW-974: remove 044 field from MARC Export
  backend/app/exporters/models/marc21.rb
  backend/spec/export_marc_spec.rb
Labels: community, import / export, update_import/export_maps

#1966 Brief form for relnotes
  Rakefile
  scripts/tasks/release_notes.rb
Labels: add_technical_documentation

#1963 Anw 849 subject form prepopulation
  frontend/app/views/terms/_template.html.erb
  frontend/spec/selenium/spec/accessions_spec.rb
  frontend/spec/selenium/spec/resources_spec.rb
  frontend/spec/selenium/spec/subjects_spec.rb
Labels: community

#1943 Search Prepopulation for Current Resource in Top Container Modal
  frontend/app/assets/javascripts/linker.js
  frontend/spec/selenium/spec/resources_spec.rb
Labels: community

#1957 Continuation of #1923 to deprecate search/subjects endpoint
  backend/app/controllers/search.rb
Labels: API, documentation

#1956 issue_1851: Add label attribute to dates for EAD exports
  backend/app/exporters/lib/export_helpers.rb
  backend/app/exporters/serializers/ead3.rb
  backend/spec/fixtures/oai/responses/getrecord_oai_ead.xml
Labels: import / export, update_import/export_maps

#1970 Don't duplicate "Errors and warnings" sidebar entry
  frontend/app/assets/javascripts/update_monitor.js
Labels: community

#1969 Agent form enhancements
  frontend/app/views/agents/_form.html.erb
  frontend/app/views/agents/show.html.erb
  frontend/spec/selenium/spec/assessments_spec.rb
Labels: community, plugins
