Repository archivesspace/archivesspace, pull requests merged in 2020-07, with the labels that each got.

#1940 Update translations for v2.8.0
  common/locales/en.yml
  common/locales/es.yml
  common/locales/fr.yml
  common/locales/ja.yml
  frontend/config/locales/es.yml
  frontend/config/locales/fr.yml
  frontend/config/locales/ja.yml
  public/config/locales/es.yml
  public/config/locales/fr.yml
  public/config/locales/ja.yml
Labels: translations

#1942 Ensure that top_container records index all linked locations
  frontend/app/views/top_containers/bulk_operations/_bulk_action_templates.html.erb
  frontend/app/views/top_containers/bulk_operations/_results.html.erb
  indexer/app/lib/indexer_common.rb
Labels: bug, indexer

#1948 Brief additional guidance for assessment rating report
  reports/assessments/assessment_rating_report/en.yml
  reports/assessments/assessment_rating_report/es.yml
  reports/assessments/assessment_rating_report/fr.yml
  reports/assessments/assessment_rating_report/ja.yml
Labels: translations

#1946 UI/relationships mixin changes for merging containers with profiles
  backend/app/model/mixins/relationships.rb
  backend/spec/controller_merge_request_spec.rb
  frontend/app/assets/javascripts/top_containers.bulk.js
  frontend/app/views/top_containers/bulk_operations/_bulk_action_templates.html.erb
  frontend/app/views/top_containers/bulk_operations/_results.html.erb
  frontend/config/locales/en.yml
  frontend/config/locales/es.yml
  frontend/config/locales/fr.yml
  frontend/config/locales/ja.yml
Labels: bug, translations

#1951 Small edit to container merger instructions
  frontend/config/locales/en.yml
  frontend/config/locales/es.yml
  frontend/config/locales/fr.yml
  frontend/config/locales/ja.yml
Labels: translations

#1950 Deprecation notice in API docs
  _yard/API.erb
  backend/app/lib/rest.rb
Labels: community, documentation

#1898 Update docs sidebar and begin redirects to tech_docs page
  CONTRIBUTING
  README.md
  common/db/db_migrator.rb
  docs/_includes/sidebar.html
  plugins/hello_world/README.md
Labels: documentation

#1891 Display location when viewing container instance
  frontend/app/assets/stylesheets/archivesspace/token-input.less
  frontend/app/controllers/accessions_controller.rb
  frontend/app/controllers/archival_objects_controller.rb
  frontend/app/controllers/resources_controller.rb
  frontend/app/views/container_locations/_show_only_token.html.erb
  frontend/app/views/sub_containers/_show.html.erb
  frontend/app/views/top_containers/_linker.html.erb
Labels: community

#1887 Top Container Sticky Search
  frontend/app/assets/javascripts/top_containers.bulk.js
  frontend/app/controllers/repositories_controller.rb
  frontend/app/controllers/top_containers_controller.rb
  frontend/app/views/top_containers/bulk_operations/_collection_accession_linker.erb
  frontend/app/views/top_containers/bulk_operations/_collection_resource_linker.erb
  frontend/app/views/top_containers/bulk_operations/_container_profile_linker.html.erb
  frontend/app/views/top_containers/bulk_operations/_location_linker.html.erb
  frontend/spec/selenium/spec/instances_and_containers_spec.rb
Labels: community

#1953 Updates
  Gemfile.lock
  Rakefile
  _yard/Gemfile.lock
  backend/Gemfile
  backend/Gemfile.lock
  backend/app/controllers/ark_name.rb
  backend/app/converters/lib/csv_converter.rb
  backend/app/lib/bootstrap.rb
  backend/app/lib/oai/aspace_oai_repository.rb
  backend/app/lib/rest.rb
  backend/app/lib/slugs/slug_helpers_generate.rb
  backend/app/model/ASModel_scoping.rb
  backend/app/model/assessment.rb
  backend/app/model/db.rb
  backend/app/model/idlookup.rb
  backend/app/model/location.rb
  backend/app/model/mixins/agent_manager.rb
  backend/app/model/mixins/relationships.rb
  backend/app/model/mixins/transferable.rb
  backend/config/warble.rb
  backend/spec/model_enumeration_spec.rb
  backend/spec/model_relationships_spec.rb
  backend/spec/relationships_spec_helper.rb
  backend/spec/spec_helper.rb
  build/build.xml
  common/db/db_migrator.rb
  common/db/migrations/034_require_dates_on_resources.rb
  common/jsonmodel_client.rb
  docs/Gemfile.lock
  docs/slate/Gemfile.lock
  frontend/Gemfile
  frontend/Gemfile.lock
  frontend/app/controllers/application_controller.rb
  frontend/app/controllers/archival_objects_controller.rb
  frontend/app/controllers/date_calculator_controller.rb
  frontend/app/controllers/digital_object_components_controller.rb
  frontend/app/controllers/digital_objects_controller.rb
  frontend/app/controllers/enumerations_controller.rb
  frontend/app/controllers/jobs_controller.rb
  frontend/app/controllers/locations_controller.rb
  frontend/app/controllers/resources_controller.rb
  frontend/app/controllers/tests_controller.rb
  frontend/app/controllers/top_containers_controller.rb
  frontend/app/helpers/export_helper.rb
  indexer/Gemfile
  indexer/Gemfile.lock
  indexer/config/warble.rb
  oai/Gemfile
  oai/Gemfile.lock
  oai/config/warble.rb
  public/Gemfile
  public/Gemfile.lock
  public/app/models/solr_results.rb
  public/config/initializers/new_framework_defaults.rb
  scripts/build_release
Labels: dependencies, gem management

#1918 ANW-1089: Fix regex for extracting barcodes from label attributes in containers in EAD importer
  backend/app/converters/ead_converter.rb
Labels: community
