Repository archivesspace/archivesspace, pull requests merged in 2020-05, with the labels that each got.

#1872 Remove skip links from show pages
  public/app/views/shared/_skipnav.html.erb
Labels: accessibility

#1854 Arcspc 658 for submission - title sort numeric-sensitive
  .gitignore
  build/build.xml
  frontend/spec/selenium/spec/locations_spec.rb
  indexer/app/lib/indexer_common.rb
  solr/lib/.gitkeep
  solr/schema.xml
Labels: community

#1871 Add missing form labels, fix empty links, add aria-labels, add fieldset
  frontend/app/helpers/application_helper.rb
  frontend/app/views/assessment_attributes/edit.html.erb
  frontend/app/views/groups/_form.html.erb
  frontend/config/locales/en.yml
  frontend/config/locales/es.yml
  frontend/config/locales/fr.yml
  frontend/config/locales/ja.yml
  frontend/vendor/assets/stylesheets/bootstrap/forms.less
Labels: accessibility

#1876 Issue #1875: Account for digital object instances
  backend/app/controllers/accession.rb
  backend/app/controllers/resource.rb
Labels: API

#1892 Membership
  README.md
Labels: documentation

#1866 ANW-1065: strip out agent contact data from indexer JSON field
  indexer/app/lib/indexer_common.rb
  indexer/app/lib/indexer_common_config.rb
  indexer/spec/factories.rb
  indexer/spec/indexer_common_spec.rb
Labels: indexer, reindex

#1864 Issue #393: Only use pagingation for calls going through handle_listing
  _yard/API.erb
  backend/app/controllers/location_profile.rb
  backend/app/controllers/search.rb
  backend/app/controllers/update_feed.rb
  backend/app/lib/rest.rb
Labels: API, documentation

#1867 Issue #1384: Use correct method for classification_terms/parent endpoint
  backend/app/controllers/classification_term.rb
  backend/app/model/classification_term.rb
  backend/spec/controller_classification_spec.rb
Labels: API

#1878 Issue #1877: Fix PDF generation via API
  backend/app/controllers/exports.rb
  backend/app/lib/export.rb
Labels: API, PDF

#1888 Top container typeahead improvements
  frontend/app/controllers/top_containers_controller.rb
  indexer/app/lib/indexer_common.rb
  solr/schema.xml
Labels: community

#1890 Improvements to top container indicator column sort
  frontend/app/assets/javascripts/top_containers.bulk.js
Labels: community

#1885 Add Has Location to Top Container search page
  frontend/app/controllers/top_containers_controller.rb
  frontend/app/views/top_containers/bulk_operations/_search_criteria.html.erb
  frontend/config/locales/en.yml
  frontend/config/locales/es.yml
  frontend/config/locales/fr.yml
  frontend/config/locales/ja.yml
  indexer/app/lib/indexer_common.rb
Labels: add_user_documentation, community, indexer, reindex

#1904 Allow repository contact to be indexed
  indexer/app/lib/indexer_common_config.rb
  indexer/spec/indexer_common_spec.rb
Labels: indexer

#1903 use indexer_log_level instead of backend_log_level
  indexer/app/main.rb
Labels: community, logging, update_release_notes

#1905 Also allow repository contact to be indexed in resolved records
  .github/workflows/indexer.yml
  indexer/app/lib/indexer_common_config.rb
  public/spec/features/accessions_spec.rb
Labels: indexer, tests
