Repository archivesspace/archivesspace, pull requests merged in 2020-11, with the labels that each got.

#2013 ANW-969: Export <langusage> from finding aid language if no note
  backend/app/exporters/serializers/ead.rb
  common/locales/en.yml
Labels: hacktoberfest-accepted, import / export

#2039 ANW-1017: Reset preference defaults
  frontend/app/controllers/preferences_controller.rb
  frontend/app/views/preferences/_toolbar.html.erb
  frontend/config/locales/en.yml
  frontend/config/locales/es.yml
  frontend/config/locales/fr.yml
  frontend/config/locales/ja.yml
  frontend/config/routes.rb
  frontend/spec/selenium/spec/user_preferences_spec.rb
Labels: feature_request, hacktoberfest-accepted

#2043 Fix collection management title sorting
  common/config/search_browse_column_config.rb
  common/db/migrations/138_reindex_collection_management.rb
  frontend/app/models/search.rb
  indexer/app/lib/indexer_common.rb
Labels: indexer, migration

#2048 Allow public plugins to use gems
  public/Gemfile
Labels: plugins

#2052 Minor tweak to #2039 translation
  frontend/config/locales/en.yml
  frontend/config/locales/es.yml
  frontend/config/locales/fr.yml
  frontend/config/locales/ja.yml
Labels: translations

#2050 Updating non-English translations for v2.8.1
  common/locales/en.yml
  common/locales/es.yml
  common/locales/fr.yml
  common/locales/ja.yml
Labels: translations

#2051 Enumerations don't need to be duplicated in the PUI
  public/config/locales/en.yml
  public/config/locales/es.yml
  public/config/locales/fr.yml
  public/config/locales/ja.yml
Labels: pui, translations

#2049 Remove tech docs, update build tasks
  _yard/rakefile.rb
  build/build.xml
  docs/BackgroundJobs.png
  docs/BackgroundJobsList.png
  docs/ConversionLog.png
  docs/ErrorReport.png
  docs/Files.png
  docs/_includes/footer.html
  docs/_includes/header.html
  docs/_includes/logo.html
  docs/_includes/sidebar.html
  docs/_layouts/en.html
  docs/_site/assets/javascripts/main.js
  docs/_site/assets/javascripts/site.js
  docs/_site/assets/stylesheets/main.css
  docs/_site/javascripts/scale.fix.js
  docs/_site/stylesheets/pygment_trac.css
  docs/_site/stylesheets/styles.css
  docs/assets/ArchivesSpace_Contributor_License_Agreements.pdf
  docs/assets/ArchivesSpace_Corporate_Contributor_License_Agreement.pdf
  docs/assets/ArchivesSpace_Individual_Contributor_License_Agreement_ICLA.pdf
  docs/assets/images/archon_collection.jpg
  docs/assets/images/archon_container.jpg
  docs/assets/images/archon_level.jpg
  docs/assets/images/archon_migrator.jpg
  docs/assets/images/at_migrator.jpg
  docs/assets/images/overview.png
  docs/assets/javascripts/main.js
  docs/assets/javascripts/site.js
  docs/assets/stylesheets/_base.sass
  docs/assets/stylesheets/_footer.sass
  docs/assets/stylesheets/_intro.sass
  docs/assets/stylesheets/_layout.sass
  docs/assets/stylesheets/_mixins.sass
  docs/assets/stylesheets/_search.sass
  docs/assets/stylesheets/_top.sass
  docs/assets/stylesheets/_utils.sass
  docs/assets/stylesheets/_vars.sass
  docs/assets/stylesheets/foundation/_functions.scss
  docs/assets/stylesheets/foundation/_settings.scss
  docs/assets/stylesheets/foundation/components/_global.scss
  docs/assets/stylesheets/foundation/components/_grid.scss
  docs/assets/stylesheets/main.sass
  docs/index.html
  docs/javascripts/scale.fix.js
  docs/stylesheets/pygment_trac.css
  docs/stylesheets/styles.css
  scripts/build_docs.rb
  scripts/pull_tech_docs.rb
Labels: build, cleanup, documentation

#2053 ANW-1156: Don't undo reordering when saving selected component
  frontend/app/assets/javascripts/tree_toolbar.js.erb
Labels: bug

#2016 ANW 1002: Map MARC 245$g to bulk dates on import
  backend/app/converters/lib/marcxml_base_map.rb
  backend/app/exporters/examples/marc/at-tracer-marc-1.xml
  backend/spec/lib_marcxml_converter_spec.rb
Labels: hacktoberfest-accepted, import / export

#2057 Additional PUI translations for 2.8.1
  public/config/locales/en.yml
  public/config/locales/es.yml
  public/config/locales/fr.yml
  public/config/locales/ja.yml
Labels: pui, translations

#2061 Hm qsa 110620
  backend/app/lib/background_job_queue.rb
  backend/app/lib/job_runners/batch_import_runner.rb
  backend/app/lib/streaming_import.rb
  backend/app/model/ASModel_crud.rb
  backend/app/model/backend_enum_source.rb
  backend/app/model/db.rb
  backend/app/model/job.rb
  backend/app/model/mixins/relationships.rb
  backend/tests/integration.rb
  common/aspace-rails/compressor.rb
  common/jsonmodel.rb
  common/jsonmodel_i18n_mixin.rb
  common/jsonmodel_type.rb
  common/locales/en.yml
  indexer/app/lib/index_batch.rb
  indexer/app/lib/indexer_common.rb
  indexer/spec/indexer_common_spec.rb
  solr/schema.xml
Labels: translations_needed

#2064 Update build status from Travis to GH Actions
  README.md
Labels: cleanup
