Repository archivesspace/archivesspace, pull requests merged in 2020-09, with the labels that each got.

#1971 PUI fix caption
  public/app/controllers/concerns/result_info.rb
Labels: add_user_documentation

#1973 Bug fix to #1964 - sync initial URL to checkbox state
  frontend/app/views/resources/_toolbar.html.erb
Labels: community

#1972 Filter csv export
  frontend/app/controllers/accessions_controller.rb
  frontend/app/controllers/agents_controller.rb
  frontend/app/controllers/assessments_controller.rb
  frontend/app/controllers/classifications_controller.rb
  frontend/app/controllers/container_profiles_controller.rb
  frontend/app/controllers/digital_objects_controller.rb
  frontend/app/controllers/events_controller.rb
  frontend/app/controllers/locations_controller.rb
  frontend/app/controllers/resources_controller.rb
  frontend/app/controllers/search_controller.rb
  frontend/app/controllers/subjects_controller.rb
  frontend/app/helpers/export_helper.rb
  frontend/app/models/search.rb
  frontend/app/views/assessments/index.html.erb
Labels: community

#1975 adds last modified and created date as default sort options
  common/config/search_browse_column_config.rb
Labels: community

#1974 Hm qsa 090220 mc
  common/aspace_i18n.rb
  frontend/app/helpers/aspace_form_helper.rb
  frontend/app/views/container_locations/_show.html.erb
  frontend/app/views/dates/_template.html.erb
  frontend/app/views/locations/show.html.erb
  frontend/app/views/shared/_largetree.html.erb
  frontend/app/views/user_defined/_show.html.erb
  frontend/config/locales/en.yml
Labels: community, translations, translations_needed

#1977 Subrecord enhancements
  frontend/app/assets/javascripts/subrecord.crud.js
  frontend/app/assets/javascripts/subrecord.too_many.js
  frontend/app/views/shared/_templates.html.erb
Labels: community

#1979 Modify backup.rb to handle large files
  launcher/backup/lib/backup.rb
Labels: community

#1980 Update bulk import functionality to run as a background job
  backend/app/controllers/bulk_import.rb
  backend/app/lib/bulk_import/agent_handler.rb
  backend/app/lib/bulk_import/bulk_import_mixins.rb
  backend/app/lib/bulk_import/bulk_import_parser.rb
  backend/app/lib/bulk_import/bulk_import_report.rb
  backend/app/lib/bulk_import/bulk_importer.rb
  backend/app/lib/bulk_import/container_instance_handler.rb
  backend/app/lib/bulk_import/digital_object_handler.rb
  backend/app/lib/bulk_import/handler.rb
  backend/app/lib/bulk_import/import_archival_objects.rb
  backend/app/lib/bulk_import/import_digital_objects.rb
  backend/app/lib/bulk_import/parent_tracker.rb
  backend/app/lib/bulk_import/subject_handler.rb
  backend/app/lib/job_runners/batch_import_runner.rb
  backend/app/lib/job_runners/bulk_import_runner.rb
  backend/app/lib/ticker.rb
  backend/app/views/bulk/bulk_import_response.erb
  backend/spec/fixtures/bulk_import/bulk_import_VFIRST01_test01.csv
  backend/spec/fixtures/bulk_import/bulk_import_VFIRST01_test01.xlsx
  backend/spec/lib_bulk_import_agent_handler_spec.rb
  backend/spec/lib_bulk_import_bulk_mixins_spec.rb
  backend/spec/lib_bulk_import_container_instance_handler_spec.rb
  backend/spec/lib_bulk_import_import_archival_objects_spec.rb
  backend/spec/lib_bulk_import_subject_handler_spec.rb
  common/locales/en.yml
  common/schemas/bulk_import_job.rb
  frontend/app/assets/javascripts/bulk_import.js.erb
  frontend/app/controllers/bulk_import_controller.rb
  frontend/app/controllers/jobs_controller.rb
  frontend/app/controllers/resources_controller.rb
  frontend/app/helpers/jobs_helper.rb
  frontend/app/views/jobs/_form.html.erb
  frontend/app/views/jobs/_job_data_cell.html.erb
  frontend/app/views/jobs/_show_templates.html.erb
  frontend/app/views/jobs/show.html.erb
  frontend/app/views/resources/_bulk_import_form.html.erb
  frontend/app/views/resources/_bulk_import_response.html.erb
  frontend/app/views/shared/_flash_messages.html.erb
  frontend/config/locales/en.yml
  frontend/config/routes.rb
  frontend/spec/selenium/spec/bulk_import_spec.rb
  indexer/app/lib/indexer_common.rb
  templates/bulk_import_DO_template.csv
  templates/bulk_import_template.csv
  templates/bulk_import_template.xlsx
Labels: add_user_documentation, contractor, indexer, translations_needed

#1981 Hm qsa 091520 mc
  backend/app/controllers/enumeration.rb
  backend/app/model/enumeration.rb
  backend/spec/rest_enumerations_spec.rb
  frontend/app/controllers/enumerations_controller.rb
  frontend/app/views/accessions/_toolbar.html.erb
  frontend/app/views/agents/_toolbar.html.erb
  frontend/app/views/enumerations/index.html.erb
  frontend/app/views/shared/_component_toolbar.html.erb
  frontend/app/views/shared/_resource_toolbar.html.erb
  frontend/config/locales/en.yml
  frontend/config/routes.rb
Labels: community
