Repository archivesspace/archivesspace, pull requests merged in 2020-04, with the labels that each got.

#1830 ANW-921 PUI citation tabs
  public/app/assets/javascripts/cite.js
  public/app/models/archival_object.rb
  public/app/models/digital_object.rb
  public/app/models/resource.rb
  public/app/views/cite/_modal_tabbed.html.erb
  public/app/views/cite/show.html.erb
  public/app/views/shared/_modal_actions.html.erb
Labels: in progress

#1825 Modify the view published button in the staff interface toolbar
  frontend/app/views/accessions/_toolbar.html.erb
  frontend/app/views/agents/_toolbar.html.erb
  frontend/app/views/shared/_component_toolbar.html.erb
  frontend/app/views/shared/_resource_toolbar.html.erb
  frontend/app/views/shared/_view_published_button.html.erb
Labels: community

#1810 Option for preferences to set locale
  common/aspace_i18n.rb
  common/config/preference_defaults.rb
  common/jsonmodel.rb
  common/locales/en.yml
  common/locales/es.yml
  common/locales/fr.yml
  common/locales/ja.yml
  common/schemas/defaults.rb
  frontend/app/controllers/application_controller.rb
  frontend/app/helpers/application_helper.rb
  frontend/app/views/defaults/_template.html.erb
  frontend/config/application.rb
Labels: translations

#1857 ANW-292: Correct conflicting record error on authority id collision
  backend/app/lib/crud_helpers.rb
  backend/app/model/mixins/agent_manager.rb
  backend/spec/controller_agent_software_spec.rb
  backend/spec/controller_conflict_reporting_spec.rb
  backend/spec/factories.rb
  backend/spec/model_agent_software_spec.rb
  common/locales/en.yml
  common/locales/es.yml
  common/locales/fr.yml
  common/locales/ja.yml
Labels: API, translations

#1832 Change PUI container display page search results title ANW-867
  public/app/views/containers/show.html.erb
  public/config/locales/en.yml
  public/config/locales/es.yml
  public/config/locales/fr.yml
  public/config/locales/ja.yml
Labels: community, translations, update_release_notes

#1863 Updated API docs with general information section.
  _yard/API.erb
  docs/api/index.html
  docs/slate/source/index.md
Labels: API, community, documentation

#1861 ANW-806-pui-and-search
  backend/spec/model_solr_spec.rb
  indexer/app/lib/large_tree_doc_indexer.rb
  public/app/controllers/concerns/searchable.rb
Labels: in progress

#1869 Enable Luke request handler
  solr/solrconfig.xml
Labels: community

#1852 Date filter fixes
  public/app/controllers/concerns/searchable.rb
  public/app/models/search.rb
  public/app/views/shared/_facets.html.erb
  public/app/views/shared/_search_collection_form.html.erb
Labels: community

#1874 Minor changes to staff and public side error pages
  frontend/public/404.html
  frontend/public/422.html
  frontend/public/500.html
  public/public/404.html
  public/public/422.html
  public/public/500.html
Labels: accessibility

#1807 ANW-805: Change logic for when dao/daogrp/daolink get "internal" audience attributes
  backend/app/exporters/serializers/ead.rb
  backend/app/exporters/serializers/ead3.rb
  backend/spec/export_ead3_spec.rb
  backend/spec/export_ead_spec.rb
Labels: community

#1844 Generalized table improvements to core
  frontend/app/assets/stylesheets/archivesspace/tables.less
  frontend/app/assets/stylesheets/archivesspace/top_containers_bulk.less
  frontend/app/controllers/search_controller.rb
  frontend/app/helpers/search_helper.rb
  frontend/app/models/search.rb
  frontend/app/views/agents/show.html.erb
  frontend/app/views/locations/show.html.erb
  frontend/app/views/search/_embedded.html.erb
  frontend/app/views/search/_listing.html.erb
  frontend/app/views/search/_results.html.erb
  frontend/app/views/top_containers/bulk_operations/_results.html.erb
  frontend/config/locales/en.yml
  frontend/spec/controllers/search_controller_spec.rb
  frontend/spec/selenium/spec/events_spec.rb
  frontend/spec/spec_helper.rb
  indexer/app/lib/indexer_common.rb
Labels: community

#1860 ANW-172: Add all dates to ao and do records h2
  backend/app/model/archival_object.rb
  backend/app/model/digital_object_component.rb
  backend/spec/model_archival_object_spec.rb
  backend/spec/model_digital_object_component_spec.rb
  common/db/migrations/132_update_display_string.rb
  common/locales/en.yml
  common/locales/es.yml
  common/locales/fr.yml
  common/locales/ja.yml
Labels: migration, translations
