Repository archivesspace/archivesspace, pull requests merged in 2021-06, with the labels that each got.

#2285 pend two tests that fail frequently
  frontend/spec/selenium/spec/default_values_spec.rb
  frontend/spec/selenium/spec/trees_spec.rb
Labels: tests

#2274 ANW-1013: Update error message for regex mismatch to be more user friendly
  common/locales/en.yml
  common/locales/es.yml
  common/locales/fr.yml
  common/locales/ja.yml
Labels: translations, translations_needed

#2301 Ensure object being viewed is an archival object
  public/app/views/objects/show.html.erb
Labels: pui

#2290 ANW-915 Add language and script of description to accession records
  backend/app/converters/accession_converter.rb
  backend/app/exporters/examples/accession/aspace_accession_import_template.csv
  backend/spec/controller_accession_spec.rb
  backend/spec/controller_default_values_spec.rb
  common/db/migrations/151_add_language_script_of_desc_accession.rb
  common/locales/en.yml
  common/locales/es.yml
  common/locales/fr.yml
  common/locales/ja.yml
  common/schemas/accession.rb
  frontend/app/views/accessions/_form.html.erb
  frontend/app/views/accessions/show.html.erb
  public/app/models/accession.rb
  public/app/views/accessions/show.html.erb
  public/config/locales/en.yml
  public/config/locales/es.yml
  public/config/locales/fr.yml
  public/config/locales/ja.yml
  public/spec/controllers/accessions_controller_spec.rb
  public/spec/features/accessions_spec.rb
  public/spec/spec_helper.rb
Labels: add_user_documentation, migration, templates

#2303 Renumber duplicate 151 migration
  common/db/migrations/152_add_language_script_of_desc_accession.rb
Labels: migration

#2295 ANW-1096: display deaccessions in public interface for resources
  public/app/models/resource.rb
  public/app/views/shared/_record_innards.html.erb
  public/spec/controllers/accessions_controller_spec.rb
  public/spec/controllers/resources_controller_spec.rb
  public/spec/features/accessions_spec.rb
  public/spec/features/resources_spec.rb
  public/spec/spec_helper.rb
Labels: pui

#2302 ANW-908: Add langmaterials to accessions
  backend/app/converters/accession_converter.rb
  backend/app/exporters/examples/accession/aspace_accession_import_template.csv
  backend/app/model/accession.rb
  backend/spec/controller_accession_spec.rb
  backend/spec/controller_default_values_spec.rb
  common/db/migrations/153_add_langmaterials_accession.rb
  common/schemas/accession.rb
  frontend/app/assets/javascripts/accessions.crud.js
  frontend/app/views/accessions/_form.html.erb
  frontend/app/views/accessions/_sidebar.html.erb
  frontend/app/views/accessions/show.html.erb
  public/app/models/accession.rb
  public/app/models/record.rb
  public/spec/controllers/accessions_controller_spec.rb
  public/spec/factories.rb
  public/spec/features/accessions_spec.rb
  public/spec/spec_helper.rb
Labels: add_user_documentation, migration, templates

#2315 ANW-1332 Adjust color contrast for non-text elements
  frontend/vendor/assets/stylesheets/bootstrap/variables.less
  public/app/assets/stylesheets/archivesspace/colors.scss
Labels: accessibility

#2316 ANW-1330 Darken active breadcrumb text in SUI
  frontend/vendor/assets/stylesheets/bootstrap/variables.less
Labels: accessibility

#2317 ANW-1321 Ensure color contrast in PUI footer on hover/focus
  public/app/assets/stylesheets/archivesspace/aspace.scss
Labels: accessibility

#2319 ANW-1311 Darken placeholder text on PUI
  public/app/assets/stylesheets/application.scss
  public/app/assets/stylesheets/archivesspace/variables.scss
Labels: accessibility

#2321 ANW-1315 Don't duplicate ids in PUI
  public/Gemfile
  public/Gemfile.lock
  public/app/assets/javascripts/request.js
  public/app/views/repositories/_badge.html.erb
  public/app/views/resources/infinite.html.erb
  public/spec/features/accessibility_spec.rb
  public/spec/spec_helper.rb
Labels: accessibility

#2323 ANW-1313 Provide more descriptive labels in PUI record sidebar, search
  frontend/app/assets/javascripts/largetree.js.erb
  frontend/app/assets/javascripts/tree_renderers.js.erb
  public/app/assets/javascripts/tree_renderer.js.erb
  public/app/views/shared/_search.html.erb
  public/config/locales/en.yml
  public/config/locales/es.yml
  public/config/locales/fr.yml
  public/config/locales/ja.yml
Labels: accessibility
