Repository archivesspace/archivesspace, pull requests merged in 2021-11, with the labels that each got.

#2519 ANW-1388 Add subject merge api examples
  backend/app/controllers/merge_request.rb
Labels: documentation, API

#2518 ANW-1294 Indicate required permissions for endpoints in API docs
  _yard/API.erb
  backend/app/lib/rest.rb
Labels: documentation, API

#2512 Fix Selector to Correctly Collapse Nodes for ANW-1443
  frontend/app/assets/javascripts/largetree.js.erb
Labels: community

#2523 ANW-1335 Fix API examples for arrays
  _yard/API.erb
  backend/spec/documentation_spec.rb
Labels: documentation, API

#2515 ANW-1292 Clarify /root API endpoints
  backend/app/controllers/classification.rb
  backend/app/controllers/digital_object.rb
  backend/app/controllers/resource.rb
  backend/app/controllers/tree_docs.rb
Labels: documentation, API

#2488 ANW-1337: Improve public modal screen reader accessibility
  public/app/assets/javascripts/cite.js
  public/app/assets/javascripts/request.js
  public/app/assets/stylesheets/application.scss
  public/app/assets/stylesheets/archivesspace/aspace.scss
  public/app/assets/stylesheets/archivesspace/helpers.scss
  public/app/views/cite/_modal_body.html.erb
  public/app/views/cite/_modal_tabbed.html.erb
  public/app/views/shared/_modal.html.erb
  public/app/views/shared/_modal_actions.html.erb
  public/config/locales/en.yml
  public/config/locales/es.yml
  public/config/locales/fr.yml
  public/config/locales/ja.yml
  public/config/locales/pt.yml
  public/spec/features/cite_spec.rb
Labels: accessibility, tests, pui
