Repository archivesspace/archivesspace, pull requests merged in 2021-05, with the labels that each got.

#2243 ANW-1029: CSS fixes for small mobile devices (up to 480 px width)
  public/app/assets/stylesheets/archivesspace/aspace.scss
Labels: accessibility, pui

#2251 Update to #2084 subjects API documentation
  backend/app/controllers/subject.rb
Labels: API, documentation

#2248 ANW-1074 MARCXML import 520 ind1="2" to scopecontent
  backend/app/converters/lib/marcxml_bib_base_map.rb
  backend/app/exporters/examples/marc/at-tracer-marc-1.xml
  backend/spec/lib_marcxml_bib_converter_spec.rb
Labels: import / export, update_import/export_maps

#2246 ANW-143 MARCXML 008 position 6 should be 's' when date type is single
  backend/app/exporters/models/marc21.rb
  backend/spec/export_marc_spec.rb
Labels: import / export, update_import/export_maps

#2250 ANW-1277 Don't display skiplinks on classification terms pages
  public/app/views/shared/_skipnav.html.erb
Labels: accessibility, pui

#2227 ANW-665: Bugfix for public interface search additional fields disappearing
  public/app/assets/javascripts/search.js.erb
  public/app/views/shared/_search.html.erb
  public/spec/features/search_spec.rb
Labels: pui

#2220 ANW-1196: optional display of identifiers in record trees
  backend/app/model/large_tree_resource.rb
  common/config/config-defaults.rb
  frontend/app/assets/javascripts/tree_renderers.js.erb
  frontend/spec/selenium/spec/resources_spec.rb
  public/app/assets/javascripts/tree_renderer.js.erb
  public/config/locales/en.yml
  public/config/locales/es.yml
  public/config/locales/fr.yml
  public/config/locales/ja.yml
  public/spec/rails_helper.rb
  public/spec/spec_helper.rb
Labels: community

#2268 Ensure @marc1 always has an inclusive date
  backend/spec/export_marc_spec.rb
Labels: tests

#2270 Post-3.0 updates to LCNAF plugin tests
  plugins/lcnaf/frontend/spec/lcnaf_client_spec.rb
Labels: plugins, tests

#2238 ANW-667: Display related accessions on accession show page in PUI
  common/schemas/accession.rb
  indexer/app/lib/indexer_common.rb
  indexer/app/lib/indexer_common_config.rb
  indexer/spec/indexer_common_config_spec.rb
  public/app/models/accession.rb
  public/app/views/accessions/_related_accessions.html.erb
  public/app/views/shared/_record_innards.html.erb
  public/config/locales/en.yml
  public/spec/controllers/accessions_controller_spec.rb
  public/spec/factories.rb
  public/spec/features/accessions_spec.rb
  public/spec/spec_helper.rb
Labels: pui

#2253 Issue #1584 Update EAD export for telephones subrecord
  backend/app/exporters/models/ead.rb
  backend/app/exporters/serializers/ead3.rb
  backend/spec/export_ead3_spec.rb
  backend/spec/export_ead_spec.rb
  backend/spec/factories.rb
  backend/spec/spec_helper.rb
Labels: bug, import / export, update_import/export_maps

#2277 Don't drop agent contact notes on migration
  common/db/migrations/142_update_existing_tables_for_agents.rb
Labels: migration
