Repository archivesspace/archivesspace, pull requests merged in 2021-09, with the labels that each got.

#2384 ANW-1282-fix-translation-errors-for-collapsed-license-view
  common/locales/enums/en.yml
  frontend/app/views/metadata_rights_declarations/_show.html.erb
  frontend/app/views/metadata_rights_declarations/_show_fields.html.erb
Labels: translations_needed

#2395 Translations update from Weblate
  frontend/config/locales/help/es.yml
Labels: translations

#2404 Enumerations translations updates and start linter implementation
  .yamllint
  common/locales/enums/en.yml
  common/locales/enums/es.yml
  common/locales/enums/fr.yml
  common/locales/enums/ja.yml
Labels: translations

#2430 Add API tree examples and improve parameters/data styling
  _yard/API.erb
  backend/app/controllers/classification.rb
  backend/app/controllers/digital_object.rb
  backend/app/controllers/resource.rb
Labels: documentation, API

#2431 ANW-1305 API examples and permissions
  backend/app/controllers/custom_report_template.rb
  backend/app/controllers/reports.rb
Labels: documentation, API
