Repository archivesspace/archivesspace, pull requests merged in 2021-04, with the labels that each got.

#2187 ANW-1238 marc auth collection
  backend/app/converters/lib/marcxml_auth_agent_base_map.rb
  backend/app/exporters/examples/marc/marcxml_collection_with_multiple_records.xml
  backend/spec/lib_marcxml_auth_agent_converter_spec.rb
Labels: agents, import / export

#2174 ANW-913: Show warning when trying to merge 2 agents that have a relationship
  frontend/app/controllers/agents_controller.rb
  frontend/config/locales/en.yml
  frontend/spec/selenium/spec/agents_spec.rb
Labels: agents

#2189 ANW-1219 Add resource title and identifier to ao citations
  public/app/models/archival_object.rb
Labels: pui

#2182 ANW-1248: Improve combobox accessibility
  frontend/app/helpers/aspace_form_helper.rb
  frontend/spec/selenium/spec/accessions_spec.rb
  frontend/spec/selenium/spec/classifications_spec.rb
  frontend/spec/selenium/spec/notes_spec.rb
  frontend/spec/selenium/spec/resources_spec.rb
  frontend/vendor/assets/javascripts/bootstrap-combobox.js
Labels: accessibility

#2186 ANW-1151, ANW-1173 Don't try to create empty langmaterial note
  backend/app/converters/ead_converter.rb
Labels: import / export

#2201 ANW-1234: Update translation values for agent relationship types
  common/locales/en.yml
Labels: agents, translations

#2202 Set publish on subnotes the same as parent multi-part note in EAD importer
  backend/app/converters/ead_converter.rb
Labels: import / export, update_import/export_maps

#2200 ANW-1231: Add tooltip for related agents fields
  common/locales/en.yml
  frontend/app/views/agents/_linker.html.erb
  frontend/app/views/related_agents/_template.html.erb
Labels: agents, translations

#2196 ANW-1261: Update translation files for foreign languages
  common/locales/enums/es.yml
  common/locales/enums/fr.yml
  common/locales/enums/ja.yml
  common/locales/es.yml
  common/locales/fr.yml
  common/locales/ja.yml
  frontend/config/locales/es.yml
  frontend/config/locales/fr.yml
  frontend/config/locales/help/es.yml
  frontend/config/locales/help/fr.yml
  frontend/config/locales/help/ja.yml
  frontend/config/locales/ja.yml
  public/config/locales/es.yml
  public/config/locales/fr.yml
  public/config/locales/ja.yml
Labels: agents, translations

#2192 ANW-1174 Import MARC extents that include only numbers and commas
  backend/app/converters/lib/marcxml_bib_base_map.rb
Labels: import / export

#2205 ANW-1199: Updating help links
  frontend/app/views/agents/_form.html.erb
  frontend/app/views/agents/_merge_selector.html.erb
  frontend/app/views/agents/required.html.erb
  frontend/app/views/related_agents/_form.html.erb
  frontend/config/help.yml
Labels: agents

#2207 ANW-1083: MARCXML import field 730
  backend/app/converters/lib/marcxml_bib_base_map.rb
Labels: community, import / export

#2212 Anw 977 publish partial trees
  backend/app/controllers/archival_object.rb
  backend/app/controllers/resource.rb
  backend/spec/controller_archival_object_spec.rb
  backend/spec/controller_resource_spec.rb
  frontend/app/controllers/archival_objects_controller.rb
  frontend/app/controllers/resources_controller.rb
  frontend/app/views/shared/_component_toolbar.html.erb
  frontend/app/views/shared/_resource_toolbar.html.erb
  frontend/config/locales/en.yml
  frontend/config/locales/es.yml
  frontend/config/locales/fr.yml
  frontend/config/locales/ja.yml
  frontend/config/routes.rb
  frontend/spec/selenium/spec/resources_spec.rb
Labels: community

#2211 ANW-1267 Remove default source and rules from MARCXML Auth Importer
  backend/app/converters/lib/marcxml_auth_agent_base_map.rb
Labels: agents, import / export

#2204 ANW-1253: Bugfix for merging linked top containers into unassociated top container
  backend/app/model/mixins/relationships.rb
  backend/spec/controller_merge_request_spec.rb
  common/db/migrations/146_tc_link_cleanup.rb
Labels: bug, migration

#2215 ANW-1269: Updating tooltip labels for help links
  frontend/app/views/agents/_form.html.erb
  frontend/config/help.yml
  frontend/config/locales/help/en.yml
Labels: agents, translations_needed

#2213 ANW-1036: Adding dates field from name form to sort name string for software
  backend/app/model/mixins/sort_name_processor.rb
  backend/spec/model_agent_corporate_entity_spec.rb
  backend/spec/model_agent_family_spec.rb
  backend/spec/model_agent_person_spec.rb
  backend/spec/model_agent_software_spec.rb
Labels: agents

#2214 ANW-1259 MARCXML Auth import 035 prepended with (DLC) source and type
  backend/app/converters/lib/marcxml_auth_agent_base_map.rb
  backend/app/exporters/examples/marc/authority_john_davis_2.xml
  backend/spec/lib_marcxml_auth_agent_converter_spec.rb
Labels: agents, import / export, update_import/export_maps

#2216 ANW-1266: For EAC agents export, use string "Revised" instead of "Revised/Corre…
  backend/app/exporters/serializers/eac.rb
  backend/spec/export_eac_spec.rb
Labels: agents, import / export

#2217 ANW-1232: JSON validations for software agents excised fields
  backend/spec/controller_agent_software_spec.rb
  backend/spec/controller_exports_spec.rb
  backend/spec/factories.rb
  backend/spec/model_agent_software_spec.rb
  common/locales/en.yml
  common/validations.rb
Labels: agents, translations_needed

#2225 ANW-814 Map EAD role attribute to linked agent relator
  backend/app/converters/ead_converter.rb
  backend/app/exporters/examples/ead/at-tracer.xml
  backend/spec/lib_ead_converter_spec.rb
Labels: import / export, update_import/export_maps

#2222 ANW-234 Import accession_cataloged_note to event record outcome note
  backend/app/converters/accession_converter.rb
  backend/spec/lib_accession_converter_spec.rb
Labels: bug, import / export, update_import/export_maps

#2228 ANW-825: Don't include $0 in MARC export if $v, $x, $y, or $z
  backend/app/exporters/models/marc21.rb
  backend/spec/export_marc_spec.rb
Labels: bug, import / export, update_import/export_maps

#2224 Fix local access restriction enum search
  backend/app/model/rights_restriction_type.rb
  indexer/app/lib/indexer_common.rb
Labels: bug

#2226 ANW-1264: Implementing updated EAC export map for agent dates
  backend/app/exporters/serializers/eac.rb
  backend/spec/export_eac_spec.rb
Labels: agents, import / export

#2230 ANW-1212 Exclude unpublished file versions from PUI PDF output
  public/app/views/pdf/_digital_object_links.html.erb
Labels: PDF, pui

#2231 ANW-211 PUI record badge should only show archival objects
  public/app/controllers/repositories_controller.rb
  public/app/views/repositories/_badge.html.erb
  public/spec/factories.rb
  public/spec/features/repositories_spec.rb
  public/spec/spec_helper.rb
Labels: pui

#2223 ANW-90 Map telephone and fax to agent contact telephones subrecord
  backend/app/converters/accession_converter.rb
  backend/spec/lib_accession_converter_spec.rb
Labels: bug, import / export, update_import/export_maps

#2236 ANW-1253 cont'd - migration 146 logging cleanup
  common/db/migrations/146_tc_link_cleanup.rb
Labels: migration

#2218 ANW-1265 Improve linker box accessibility
  frontend/app/assets/javascripts/jquery.tokeninput.js
  frontend/app/assets/javascripts/linker.js
  frontend/app/views/accessions/_linker.html.erb
  frontend/app/views/agents/_linker.html.erb
  frontend/app/views/classification_terms/_linker.html.erb
  frontend/app/views/classification_terms/_record_linker.html.erb
  frontend/app/views/classifications/_linker.html.erb
  frontend/app/views/classifications/_record_linker.html.erb
  frontend/app/views/container_profiles/_linker.html.erb
  frontend/app/views/digital_objects/_linker.html.erb
  frontend/app/views/events/_record_linker.html.erb
  frontend/app/views/location_profiles/_linker.html.erb
  frontend/app/views/locations/_linker.html.erb
  frontend/app/views/repositories/_linker.html.erb
  frontend/app/views/resources/_linker.html.erb
  frontend/app/views/shared/_linker.html.erb
  frontend/app/views/subjects/_linker.html.erb
  frontend/app/views/top_containers/_linker.html.erb
Labels: accessibility

#2232 ANW-1047 Update 1xx, 6xx, and 7xx to export both $e and $4 if relator
  backend/app/exporters/models/marc21.rb
  backend/spec/export_marc_spec.rb
Labels: bug, import / export, update_import/export_maps

#2235 ANW-1207: Digital Object suppress link to unpublished accessions
  public/app/models/digital_object.rb
  public/spec/features/digital_objects_spec.rb
  public/spec/spec_helper.rb
Labels: bug, pui

#2239 ANW-861: Show date certainty in parens next to date in PUI
  public/app/models/record.rb
  public/spec/factories.rb
  public/spec/features/resources_spec.rb
Labels: pui

#2229 ANW-853 Remove location info from PUI request form / emails
  public/app/models/record.rb
  public/app/models/request_item.rb
Labels: pui

#2240 ANW-963: CSS fix for correctly styling bold tag in mixed note content in the PUI
  public/app/assets/stylesheets/archivesspace/mixed-content.scss
Labels: pui

#2242 ANW-90 don't attempt to import extension without telephone number
  backend/app/converters/accession_converter.rb
Labels: import / export
