Repository archivesspace/archivesspace, pull requests merged in 2021-10, with the labels that each got.

#2445 update copyright statement
  COPYING
Labels: documentation, hacktoberfest-accepted

#2446 ANW-1303 hide generated uri section of jobs page if the job does not…
  backend/app/model/job.rb
  backend/spec/model_job_spec.rb
  common/schemas/job.rb
  frontend/app/views/jobs/_sidebar.html.erb
  frontend/app/views/jobs/show.html.erb
  frontend/spec/controllers/jobs_controller_spec.rb
Labels: hacktoberfest-accepted

#2503 ANW-1305 update: Remove narrow_by
  backend/app/controllers/custom_report_template.rb
Labels: documentation, API
