Repository archivesspace/archivesspace, pull requests merged in 2024-02, with the labels that each got.

#3094 Provide cfg to enable setting db pool timeout
  backend/app/model/db.rb
  common/config/config-defaults.rb
Labels: config_changes

#3093 Java 17 initial updates
  Dockerfile
  backend/app/controllers/system.rb
  backend/app/main.rb
  backend/app/model/db.rb
  backend/spec/backend_spec.rb
  build/ant/ant-launcher.jar
  build/ant/ant.jar
  build/build.xml
Labels: add_technical_documentation

#3098 Solr updates
  .devcontainer/Dockerfile
  .devcontainer/build_and_push
  .devcontainer/build_local
  .github/workflows/accessibility.yml
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  .github/workflows/public.yml
  backend/app/model/solr.rb
  backend/spec/model_solr_spec.rb
  solr/Dockerfile
  solr/solrconfig.xml
Labels: add_technical_documentation

#3086 HTML Language Declaration
  frontend/app/views/layouts/application.html.erb
  public/app/views/layouts/application.html.erb
Labels: community
